### ISSUE TITLE
Booted time is incorrect

### ISSUE THREAD

**Issue by bart-man53** [tve/sensorgnome-build#13]
I just booted it (after a day or so without power) and booted time states: 2,7 days ago

**Comment by bart-man53** [comment]
It seems to have a delay, it is correct after 5 minutes.

**Comment by tve** [comment]
Following up... What happens is that there are two ways to get the time of the last boot and both have issues:
- the kernel records the boot time very early and makes it available as unix timestamp in /proc/stat
- the kernel provides the number of clock ticks elapsed since boot in /proc/uptime

The issue is that the rPi doesn't have a battery-backed real-time clock. So when it powers up (and I believe also when it reboots) it comes up with the last time saved to a disk (sd-card) file. This means the recorded boot time may be a bit off or wildly off.
The sensorgnome web interface calculates the boot time as "now - uptime", i.e., using the current time and the value from /proc/uptime. This means that until the system's clock is brought up to the proper current time (via NTP or GPS) it displays an inaccurate boot time but at least it eventually gets corrected.
I'm not aware of any magic solution here...
